# Generated by Django 3.0.6 on 2020-06-17 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200616_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='detail',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 689391)),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 689391)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 14, 25, 51, 673755)),
        ),
    ]
